language: cpp

compiler:
  - gcc
  - clang

before_install:
  # No SDL2 in the default repos yet
  - sudo apt-add-repository ppa:zoogie/sdl2-snapshots -y
  # GCC 4.8 not in the repos either
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get install -qq g++-4.8 # Needed for newer stdlib
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - sudo apt-get -qq install cmake build-essential libsdl2-dev libsdl2-ttf-dev bison flex libpng-dev

install:
  - cd $TRAVIS_BUILD_DIR
  - cmake .

script:
  - make -j2

notifications:
  irc:
    channels:
      - "irc.oftc.net#freerct"
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    use_notice: true
    skip_join: true

env:
  global:
    secure: "gUgAXzGLyEkqSuMav5PLylFL3vtDO+TetIqzivkWDP5G6Md2W4xCSxBtgORtgOSngfJFipnoSvIzRo85ZyOJXKxN+1Ayy4D+xanFHpfY5pZtdhrpd9nbUXM/XLTJ9KeCd7n8BUq3Qd1h6cEAfCwvajSavC+bll3Df3MfSxISLdI="

addons:
  coverity_scan:
    project:
      name: "FreeRCT/FreeRCT"
      description: "Build from Travis-CI"
    build_command_prepend: "cmake ."
    build_command: "make -j2"
    notification_email: freerct@gmail.com
    branch_pattern: coverity
